bank/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paydesk.urls'))
]

paydesk/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', StartView.as_view(), name='start'),
    path('login/', LoginUser.as_view(), name='login'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('logout/', logout_user, name='logout'),
    path('main/', UserMainView.as_view(), name='index'),
    path('persons/', PersonsView.as_view(), name='persons'),
    path('accounts/', AccountsView.as_view(), name='accounts'),
    path('operations/', OperationsView.as_view(), name='operations'),
    path('persons/<int:pk>/', PersonView.as_view(), name='person'),
    path('account/<int:pk>/', AccountView.as_view(), name='account'),
    path('create_person/', CreatePersonView.as_view(), name='create_person'),
    path('create_account/', CreateAccountView.as_view(), name='create_account'),
    path('add_account/<int:pk>/', AddAccountView.as_view(), name='add_account'),
    path('confirm_add_account/<int:person_id>/<int:account_id>', ConfirmAddAccountView.as_view(), name='confirm_add_account'),
    
    path('delete_person/<int:pk>/', DeletePersonView.as_view(), name='delete_person'),
    path('delete_account/<int:pk>/', DeleteAccountView.as_view(), name='delete_account'),
    
    path('create_person/<int:pk>/', UpdatePersonView.as_view(), name='edit_person'),
    path('create_account/<int:pk>/', UpdateAccountView.as_view(), name='edit_account'),
    
    path('issuance_cash/<int:pk>/', IssuanceCashView.as_view(), name='issuance_cash'),
    path('account_repl/<int:pk>/', AccountReplView.as_view(), name='account_repl'),
    path('transfer_funds/<int:pk>/', TransferFundsView.as_view(), name='transfer_funds'),
    path('pay_credit/<int:pk>/', PayCreditView.as_view(), name='pay_credit'),
    
    path('create_credit/<int:pk>/', CreateCreditView.as_view(), name='create_credit'),
    path('create_deposit/<int:pk>/', CreateDepositView.as_view(), name='create_deposit')
]

paydesk/models.py
from django.db import models
from datetime import date
from django.core.exceptions import ValidationError
from django.urls import reverse

class Person(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    birthday = models.DateField()
    itn = models.CharField(max_length=10, unique=True)
    
    @property
    def age(self):
        today = date.today()
        return today.year - self.birthday.year - (
            (today.month, today.day) < (self.birthday.month, self.birthday.day)
        )
        
    def clean(self):
        if self.birthday > date.today():
            raise ValidationError('Дата не можу бути в майбутньому.')
    
    def get_absolute_url(self):
        return reverse("person", kwargs={"pk": self.pk})
    
    
class Account(models.Model):
    CARD_TYPES = [
        ('UNIVERSAL', 'Універсальна'),
        ('DEBIT', 'Дебетова'),
        ('CREDIT', 'Кредитна'),
        ('SAVINGS', 'Ощадна')
    ]
    
    CURRENCY_TYPES = [
        ('USD', 'Долар США'),
        ('EUR', 'Євро'),
        ('UAN', 'Гривня')
    ]
    
    card_type = models.CharField(max_length=16, choices=CARD_TYPES)
    card_number = models.CharField(max_length=16, unique=True)
    pin = models.CharField(max_length=4)
    cvv = models.CharField(max_length=3)
    amount = models.FloatField(default=0)
    currency = models.CharField(max_length=3, choices=CURRENCY_TYPES)
    registration_date = models.DateField()
    valid_until = models.DateField()
    person = models.ForeignKey(Person, on_delete=models.SET_NULL, null=True, blank=True)
    
    def get_absolute_url(self):
        return reverse("account", kwargs={"pk": self.pk})

class Operation(models.Model):
    OPERATION_TYPES = [
        ('TRANSFER', 'Переказ коштів'),
        ('CASH_WITHDRAWAL', 'Видача готівки'),
        ('RECHARGE', 'Поповнення рахунку'),
        ('CREDIT_PAYMENT', 'Оплата кредиту')
    ]
    
    operation_type = models.CharField(max_length=16, choices=OPERATION_TYPES)
    operation_datetime = models.DateTimeField()
    sender_account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='sent_operations')
    recipient_account = models.ForeignKey(Account, on_delete=models.CASCADE, null=True, related_name='received_operations')
    sender_person = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='sent_operations')
    recipient_person = models.ForeignKey(Person, on_delete=models.CASCADE, null=True, related_name='received_operations')
    amount = models.FloatField()
    
class Credit(models.Model):
    limit = models.FloatField()
    dept = models.FloatField(default=0)
    interest_rate = models.FloatField()
    account = models.OneToOneField(Account, on_delete=models.CASCADE, related_name='credit')
    
class Deposit(models.Model):
    amount = models.FloatField()
    interest_rate = models.FloatField()
    account = models.OneToOneField(Account, on_delete=models.CASCADE, related_name='deposit')

paydesk/views.py
from django.shortcuts import render, redirect
from .models import *
from django.db.models import Q
from .forms import *
from .cards import *
from django.contrib import messages
from django.views.generic import TemplateView, ListView, DetailView, RedirectView, CreateView, UpdateView, DeleteView, View
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from .utils import *
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout, login

class StartView(HeaderMixin, TemplateView):
    template_name = 'paydesk/start_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(index=17)
        return dict(list(context.items()) + list(c_def.items()))

class RegisterUser(HeaderMixin, CreateView):
    form_class = RegisterAdminForm
    template_name = 'paydesk/register.html'
    success_url = reverse_lazy('login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(index=18)
        return dict(list(context.items()) + list(c_def.items()))

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('index')

class LoginUser(HeaderMixin, LoginView):
    form_class = LoginAdminForm
    template_name = 'paydesk/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(index=19)
        return dict(list(context.items()) + list(c_def.items()))

    def get_success_url(self):
        return reverse_lazy('index')

def logout_user(request):
    logout(request)
    return redirect('login')

class UserMainView(HeaderMixin, TemplateView):
    template_name = 'paydesk/index.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(index=14)
        return dict(list(context.items()) + list(c_def.items()))

class PersonsView(HeaderMixin, ListView):
    paginate_by = 5
    model = Person
    template_name = 'paydesk/persons.html'
    context_object_name = 'persons'
    
    def get_queryset(self):
        request = self.request
        search_query = request.GET.get('search', '')
        return Person.objects.filter(last_name__icontains=search_query) if search_query else Person.objects.all()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_query'] = self.request.GET.get('search', '')
        c_def = self.get_user_context(index=0)
        return dict(list(context.items()) + list(c_def.items()))
    
class AccountsView(HeaderMixin, ListView):
    paginate_by = 5
    model = Account
    template_name = 'paydesk/accounts.html'
    context_object_name = 'accounts'
    
    def get_queryset(self):
        request = self.request
        search_query = request.GET.get('search', '')
        return Account.objects.filter(person__isnull=False, card_number__icontains=search_query) if search_query else Account.objects.filter(person__isnull=False)
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['search_query'] = self.request.GET.get('search', '')
        c_def = self.get_user_context(index=1)
        return dict(list(context.items()) + list(c_def.items())) 

class OperationsView(HeaderMixin, ListView):
    paginate_by = 5
    model = Operation
    template_name = 'paydesk/operations.html'
    context_object_name = 'operations'
    
    def get_queryset(self):
        return Operation.objects.all().order_by('-operation_datetime')
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        c_def = self.get_user_context(index=2)
        return dict(list(context.items()) + list(c_def.items()))

class AddAccountView(HeaderMixin, ListView):
    paginate_by = 5
    model = Account
    template_name = 'paydesk/add_account.html'
    context_object_name = 'accounts'
    
    def get_queryset(self):
        return Account.objects.filter(person__isnull=True)
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        pk = self.kwargs['pk']
        context['person'] = Person.objects.get(id=pk)
        c_def = self.get_user_context(index=13)
        return dict(list(context.items()) + list(c_def.items()))
        
class ConfirmAddAccountView(RedirectView):
    permanent = False
    pattern_name = 'person'
    
    def get_redirect_url(self, *args, **kwargs):
        person_id = kwargs['person_id']
        account_id = kwargs['account_id']
        
        account = Account.objects.get(id=account_id)
        account.person_id = person_id
        account.save()
        
        messages.success(self.request, "Рахунок успішно додано!")
        
        person = Person.objects.get(id=person_id)
        return person.get_absolute_url()

class PersonView(HeaderMixin, DetailView):
    model = Person
    template_name = 'paydesk/person.html'
    context_object_name = 'person'
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        pk = self.kwargs['pk']
        context['accounts'] = Account.objects.filter(person_id=pk)
        c_def = self.get_user_context(index=3)
        return dict(list(context.items()) + list(c_def.items()))

class AccountView(HeaderMixin, DetailView):
    paginate_by = 5
    model = Account
    template_name = 'paydesk/account.html'
    context_object_name = 'account'
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        account = self.object
        context['operations'] = Operation.objects.filter(
            Q(sender_account=account) | Q(recipient_account=account)
        ).order_by('-operation_datetime')
        context['person'] = account.person
        context['accounts'] = Account.objects.filter(person_id=account.id)
        c_def = self.get_user_context(index=4)
        context['credit'] = Credit.objects.filter(account=account).first()
        context['deposit'] = Deposit.objects.filter(account=account).first()
        return dict(list(context.items()) + list(c_def.items()))

class CreatePersonView(HeaderMixin, CreateView):
    model = Person
    form_class = PersonForm
    template_name = 'paydesk/create_person.html'
    success_url = reverse_lazy('persons')
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Особу успішно створено!")
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(index=5)
        return dict(list(context.items()) + list(c_def.items()))
    
class UpdatePersonView(HeaderMixin, UpdateView):
    model = Person
    form_class = PersonForm
    template_name = 'paydesk/create_person.html'
    context_object_name = 'person'
    
    def form_valid(self, form):
        response = super().form_valid(form)
        person = form.instance
        messages.success(self.request, "Особу успішно оновлено!")
        return HttpResponseRedirect(person.get_absolute_url())
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(index=11)
        return dict(list(context.items()) + list(c_def.items()))
    
class CreateAccountView(HeaderMixin, CreateView):
    model = Account
    form_class = AccountForm
    template_name = 'paydesk/create_account.html'
    
    def form_valid(self, form):
        new_account = form.save()
        
        if new_account.card_type == "SAVINGS":
            return redirect('create_deposit', pk=new_account.id)
        elif new_account.card_type in ["CREDIT", "UNIVERSAL"]:
            return redirect('create_credit', pk=new_account.id)
        else:
            messages.success(self.request, "Рахунок успішно створено!")
            return redirect('accounts')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(index=6)
        return dict(list(context.items()) + list(c_def.items()))

class UpdateAccountView(HeaderMixin, UpdateView):
    model = Account
    form_class = AccountForm
    template_name = 'paydesk/create_account.html'
    context_object_name = 'account'

    def form_valid(self, form):
        account = form.save()
        messages.success(self.request, "Дані рахунку успішно оновлено!")
        return account.get_absolute_url()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['header'] = header[12]
        return context

class CreateCreditView(HeaderMixin, CreateView):
    model = Credit
    form_class = CreditForm
    template_name = 'paydesk/create_credit.html'
    
    def get_success_url(self):
        return self.object.account.get_absolute_url()
    
    def form_valid(self, form):
        account = Account.objects.get(id=self.kwargs['pk'])
        credit = form.save(commit=False)
        credit.account = account
        credit.save()
        
        messages.success(self.request, "Рахунок та кредит успішно створено!")
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.success(self.request, "Будь ласка, виправте помилки у формі.")
        return super().form_invalid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(index=15)
        return dict(list(context.items()) + list(c_def.items()))

class CreateDepositView(HeaderMixin, CreateView):
    model = Deposit
    form_class = DepositForm
    template_name = 'paydesk/create_deposit.html'
    

paydesk/templates/paydesk/account.html
{% extends 'paydesk/layout.html' %}

{% block body %}
<div class="my-card glass w-50 text-white mb-3 mx-auto mt-5">
    <div class="card-body fs-2">
        <div class="row">
            <div class="col text-secondary">Номер карти</div>
            <div class="col">{{ account.card_number }}</div>
        </div>
        <div class="row">
            <div class="col text-secondary">Тип карти</div>
            <span class="col">{{ account.get_card_type_display }}</span>
        </div>
        <div class="row">
            <div class="col text-secondary">ПІН</div>
            <div class="col">{{ account.pin }}</div>
        </div>
        <div class="row">
            <div class="col text-secondary">CVV</div>
            <div class="col">{{ account.cvv }}</div>
        </div>
        {% if account.card_type != 'CREDIT' %}
        <div class="row">
            <div class="col text-secondary">Баланс</div>
            <div class="col">{{ account.amount|floatformat:2 }}</div>
        </div> 
        {% endif %}
        <div class="row">
            <div class="col text-secondary">Валюта</div>
            <span class="col">{{ account.get_currency_display }}</span>
        </div>  
        <div class="row">
            <div class="col text-secondary">Дата реєстрації</div>
            <div class="col">{{ account.registration_date }}</div>
        </div> 
        <div class="row">
            <div class="col text-secondary">Дісний до</div>
            <div class="col">{{ account.valid_until }}</div>
        </div> 
        <div class="row">
            <div class="col text-secondary">Власник</div>
            <div class="col">{{ person.first_name }} {{ person.last_name }}</div>
        </div> 
    </div>
</div>

<div class="d-flex buttons-container w-100 justify-content-center gap-4">
    <a href="{% url 'delete_account' account.id %}" type="button" class="my-btn glass glass-hover buttons-item fs-2 text-center">
        <span><i class="fa-solid fa-trash"></i></span>
    </a>
    <a href="{% url 'edit_account' account.id %}" type="button" class="my-btn glass glass-hover buttons-item fs-2 text-center">
        <span><i class="fa-solid fa-file"></i></span>
    </a>
    <div class="btn-group text-center buttons-item">
        <button type="button" class="my-btn glass glass-hover buttons-item fs-2 dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
            <span><i class="fa-solid fa-money-check"></i></span>
        </button>
        <ul class="dropdown-menu">
        {% if account.card_type == "SAVINGS" %}
            <li><a class="dropdown-item fs-3" href="{% url 'account_repl' account.id %}">Поповнення рахунку</a></li>
        {% elif account.card_type == "UNIVERSAL" %}
            <li><a class="dropdown-item fs-3" href="{% url 'issuance_cash' account.id %}">Видача готівки</a></li>
            <li><a class="dropdown-item fs-3" href="{% url 'account_repl' account.id %}">Поповнення рахунку</a></li>
            <li><a class="dropdown-item fs-3" href="{% url 'transfer_funds' account.id %}">Переказ коштів</a></li>
            <li><a class="dropdown-item fs-3" href="{% url 'pay_credit' account.id %}">Оплатити кредит</a></li>
        {% elif account.card_type == "DEBIT" %}
            <li><a class="dropdown-item fs-3" href="{% url 'issuance_cash' account.id %}">Видача готівки</a></li>
            <li><a class="dropdown-item fs-3" href="{% url 'account_repl' account.id %}">Поповнення рахунку</a></li>
            <li><a class="dropdown-item fs-3" href="{% url 'transfer_funds' account.id %}">Переказ коштів</a></li>
        {% else %}
            <li><a class="dropdown-item fs-3" href="{% url 'issuance_cash' account.id %}">Видача готівки</a></li>
            <li><a class="dropdown-item fs-3" href="{% url 'transfer_funds' account.id %}">Переказ коштів</a></li>
            <li><a class="dropdown-item fs-3" href="{% url 'pay_credit' account.id %}">Оплатити кредит</a></li>
        {% endif %}
        </ul>
      </div>
      
    </div>
</div>

{% if deposit %}
    <div class="d-grid gap-2 col-6 mx-auto" style="max-width: 60rem;">
        <div class="my-card glass w-50 text-white mx-auto mt-5 w-100">
            <div class="card-header pb-2 text-center fs-1" style="border-bottom: 1px solid white;">
                <span>Депозит</span>
            </div>
            <div class="card-body fs-2 d-flex flex-column gap-3">
                <div class="row">
                    <div class="col text-secondary">Кількість грошей</div>
                    <div class="col">{{ deposit.amount|floatformat:2 }}</div>
                </div>
                <div class="row">
                    <div class="col text-secondary">Відсоткова ставка</div>
                    <span class="col">{{ deposit.interest_rate }}</span>
                </div>

            </div>
        </div>
    </div>
{% endif %}

{% if credit %}
    <div class="d-grid gap-2 col-6 mx-auto" style="max-width: 60rem;">
        <div class="my-card glass w-50 text-white mx-auto mt-5 w-100">
            <div class="card-header pb-2 text-center fs-1" style="border-bottom: 1px solid white;">
                <span>Кредит</span>
            </div>
            <div class="card-body fs-2 d-flex flex-column gap-3">
                <div class="row">
                    <div class="col text-secondary">Ліміт</div>
                    <div class="col">{{ credit.limit|floatformat:2 }}</div>
                </div>
                <div class="row">
                    <div class="col text-secondary">Заборгованість</div>
                    <span class="col">{{ credit.dept|floatformat:2 }}</span>
                </div>
                <div class="row">
                    <div class="col text-secondary">Відсоткова ставка</div>
                    <span class="col">{{ credit.interest_rate }}</span>
                </div>

            </div>
        </div>
    </div>
{% endif %}

<h1 class="display-4 text-center mt-5">Операції</h1>

<div class="d-grid mb-3 gap-2 col-6 mx-auto" style="min-width: 60rem;">
    {% for operation in operations %}
    <div class="my-card glass text-white mx-auto mt-5 w-100">
        <div class="card-header text-center fs-1" style="border-bottom: 1px solid white;">
            <span>{{ operation.operation_type }}</span>
        </div>
            <div class="card-body fs-2 d-flex flex-column gap-3">
                <div class="row">
                    <div class="d-flex flex-column ms-3 col">          
                        <span>{{ operation.sender_account.card_number }}</span>
                        <span>{{ operation.sender_account.get_card_type_display }}</span>
                        <span>{{ operation.sender_account.currency }}</span>
                        <span>{{ operation.sender_person.first_name }} {{ operation.sender_person.last_name }}</span>
                    </div>
                    <div class="d-flex flex-column me-3 col">
                        <span>{{ operation.recipient_account.card_number }}</span>
                        <span>{{ operation.recipient_account.get_card_type_display }}</span>
                        <span>{{ operation.recipient_account.currency }}</span>
                        <span>{{ operation.recipient_person.first_name }} {{ operation.recipient_person.last_name }}</span>
                    </div>
                </div>
            <div class="d-flex mt-auto ms-1 me-1 row border rounded">
                <span class="flex-column col">{{ operation.amount|floatformat:2 }}</span>
                <span class="flex-column col">{{ operation.operation_datetime }}</span>
            </div>
        </div>
    </div>
    {% empty %}
        <span class="fs-2 mt-5 glass rounded px-3 py-2 text-center">Пусто</span>
    {% endfor %}    
</div>
  
{% endblock %}

paydesk/templates/paydesk/account_repl.html
{% extends 'paydesk/layout.html' %}

{% block body %}
<div class="container mt-5">
    <form method="post">
        <div class="my-card glass text-white mb-3 mx-auto mt-5" style="max-width: 45rem;">
            <div class="card-body fs-2">
                {% csrf_token %}
                <div class="mb-3 d-flex">
                    <div class="col-5">
                        <label for="amount_operation" class="form-label">На балансі</label>
                    </div>
                    <div class="col-3">
                        {{ account.amount|floatformat:2 }}
                    </div>

                    <div class="col-4">
                        {{ account.currency }}
                    </div>
                </div>
                
                <div class="mb-3 d-flex">
                    <input type="text" name="amount_operation" class="form-control" placeholder="Введіть кількість грошей" value="{{ request.POST.amount_operation }}">
                </div>
            </div>
        </div>
        <div class="d-flex justify-content-center w-100">
            <button type="submit" class="my-btn glass glass-hover w-75 fs-2">Провести операцію</button>
        </div>    
    </form>
</div>
{% endblock %}

paydesk/templates/paydesk/add_account.html
{% extends 'paydesk/layout.html' %}

{% block body %}
<div class="d-grid mb-3 gap-2 col-6 mx-auto mt-5">
    {% for account in accounts %}
        <a href="{% url 'confirm_add_account' person_id=person.id account_id=account.id %}" type="button" class="btn fs-3 btn-outline-light d-flex justify-content-between">
            <span>{{ account.card_number }}</span>
            <span>{{ account.get_card_type_display }}</span>
            <span>{{ account.amount|floatformat:2 }}</span>
            <span>{{ account.currency }}</span>
        </a>
    {% empty %}
        <span class="fs-2 mt-5 glass rounded px-3 py-2 text-center">Пусто</span>
    {% endfor %}    
</div>
  
{% endblock %}

paydesk/templates/paydesk/operations.html
{% extends 'paydesk/layout.html' %}

{% block body %}
<div class="d-grid mb-3 col-6 mx-auto" style="min-width: 60rem;">
    {% for operation in operations %}
    <div class="my-card glass w-100 text-white mx-auto mt-3">
        <div class="card-header text-center fs-1" style="border-bottom: 1px solid white;">
            <span>{{ operation.operation_type }}</span>
        </div>
            <div class="card-body fs-2 d-flex flex-column gap-3">
                <div class="row">
                    <div class="d-flex flex-column ms-3 col">          
                        <span>{{ operation.sender_account.card_number }}</span>
                        <span>{{ operation.sender_account.get_card_type_display }}</span>
                        <span>{{ operation.sender_account.currency }}</span>
                        <span>{{ operation.sender_person.first_name }} {{ operation.sender_person.last_name }}</span>
                    </div>
                    <div class="d-flex flex-column me-3 col">
                        <span>{{ operation.recipient_account.card_number }}</span>
                        <span>{{ operation.recipient_account.get_card_type_display }}</span>
                        <span>{{ operation.recipient_account.currency }}</span>
                        <span>{{ operation.recipient_person.first_name }} {{ operation.recipient_person.last_name }}</span>
                    </div>
                </div>
            <div class="d-flex mt-auto ms-1 me-1 row border rounded">
                <span class="flex-column col">{{ operation.amount|floatformat:2 }}</span>
                <span class="flex-column col">{{ operation.operation_datetime }}</span>
            </div>
        </div>

    </div>
    <div class="d-flex flex-wrap mb-3"> 
        <div class="d-flex flex-column mt-auto">
        </div>
    </div>
    {% empty %}
        <span class="fs-2 mt-5 glass rounded px-3 py-2 text-center">Пусто</span>
    {% endfor %}    
</div>
  
{% endblock %}

paydesk/templates/paydesk/person.html
{% extends 'paydesk/layout.html' %}

{% block body %}
<div class="my-card glass text-white mb-3 mx-auto mt-5 w-50">
    <div class="card-body fs-2">
        <div class="row">
            <div class="col text-secondary">Ім'я</div>
            <div class="col">{{ person.first_name }}</div>
        </div>
        <div class="row">
            <div class="col text-secondary">Прізвище</div>
            <div class="col">{{ person.last_name }}</div>
        </div>
        <div class="row">
            <div class="col text-secondary">ІПН</div>
            <div class="col">{{ person.itn }}</div>
        </div>
        <div class="row">
            <div class="col text-secondary">Вік</div>
            <div class="col">{{ person.age }}</div>
        </div>    
    </div>
</div>
<div class="d-flex buttons-container w-100 justify-content-center gap-2">
    <a href="{% url 'delete_person' person.id %}" type="button" class="my-btn glass glass-hover fs-2 text-center w-25">
        <span><i class="fa-solid fa-trash"></i></span>
    </a>
    <a href="{% url 'edit_person' person.id %}" type="button" class="my-btn fs-2 glass glass-hover text-center w-25">
        <span><i class="fa-solid fa-file"></i></span>
    </a>
</div>

<h1 class="display-4 text-center mt-5">Список рахунків</h1>
<div class="d-grid gap-2 col-6 mx-auto mt-5">
    <a href="{% url 'add_account' pk=person.id %}" type="button" class="my-btn fs-2 glass glass-hover text-center">
        <span><i class="fa-solid fa-plus"></i></span>
    </a>
</div>

<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        {% for account in accounts %}
            <div class="carousel-item {% if forloop.first %}active{% endif %}">
                <div class="my-card glass text-white mb-5 mx-auto mt-5 w-50">
                    <div class="card-body fs-2">
                        <div class="row">
                            <div class="col text-secondary">Номер карти</div>
                            <div class="col">{{ account.card_number }}</div>
                        </div>
                        <div class="row">
                            <div class="col text-secondary">Тип карти</div>
                            <span class="col">{{ account.get_card_type_display }}</span>
                        </div>
                        <div class="row">
                            <div class="col text-secondary">ПІН</div>
                            <div class="col">{{ account.pin }}</div>
                        </div>
                        <div class="row">
                            <div class="col text-secondary">CVV</div>
                            <div class="col">{{ account.cvv }}</div>
                        </div>
                        {% if account.card_type != 'CREDIT' %}
                        <div class="row">
                            <div class="col text-secondary">Баланс</div>
                            <div class="col">{{ account.amount|floatformat:2 }}</div>
                        </div> 
                        {% endif %}
                        <div class="row">
                            <div class="col text-secondary">Валюта</div>
                            <span class="col">{{ account.get_currency_display }}</span>
                        </div>  
                        <div class="row">
                            <div class="col text-secondary">Дата реєстрації</div>
                            <div class="col">{{ account.registration_date }}</div>
                        </div> 
                        <div class="row">
                            <div class="col text-secondary">Дісний до</div>
                            <div class="col">{{ account.valid_until }}</div>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="carousel-item active">
                <div class="card glass rounded text-white text-center  mb-3 mx-auto mt-5 w-50">
                    <div class="card-body fs-2">
                        <span>Пусто</span>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>


{% endblock %}